# Generated by Django 2.2.8 on 2021-01-28 17:24

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=16)),
                ('curriculum', models.TextField()),
                ('ects', models.PositiveIntegerField()),
                ('full_time_semester', models.PositiveIntegerField()),
                ('part_time_semester', models.PositiveIntegerField()),
                ('optional', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default=courses.models.OptionalChoices('no'), max_length=8)),
            ],
        ),
    ]
