# Generated by Django 2.2.8 on 2021-01-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
