# Generated by Django 2.2.8 on 2021-01-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210128_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
