# Generated by Django 2.2.8 on 2021-01-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210128_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PROFESSOR', 'professor'), ('STUDENT', 'student')], max_length=32),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='status',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('NONE', 'none'), ('FULL_TIME', 'full time'), ('PART_TIME', 'part time')], max_length=16),
        ),
    ]
