# Generated by Django 2.2.8 on 2021-01-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210128_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('PROFESSOR', 'professor'), ('STUDENT', 'student')], max_length=32),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='status',
            field=models.CharField(choices=[('NONE', 'none'), ('FULL_TIME', 'full time'), ('PART_TIME', 'part time')], max_length=16),
        ),
    ]
