# Generated by Django 2.2.8 on 2021-02-09 17:16

from django.db import migrations, models
import users.enums


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210130_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('PROFESSOR', 'professor'), ('STUDENT', 'student')], default=users.enums.RoleChoices('student'), max_length=32),
        ),
    ]
